### Checking the processing speed of python list vs numpy array

In [1]:
import time
import numpy as np

vector_size = 10000

def python_version():
    t1 = time.time()
    X = range(vector_size)
    Y = range(vector_size)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(vector_size)
    Y = np.arange(vector_size)
    Z = X + Y
    return time.time() - t1


t1 = python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

0.003136157989501953 0.00011420249938964844
Numpy is in this example 27.461377870563673 faster!


np.array to convert/create a list object into a numpy array object

In [2]:
array1 = np.array([1, 4, 2, 5, 3])

In [3]:
array2 = np.array([3.14, 4, 2, 3])

In [4]:
array3 = np.array([[1,2,3],[4,5,6]])

In [5]:
array4 = np.array([1, 2, 3, 4], dtype='float32')

In [6]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([1.3, 3.4, 5.6, 7.8])

display(a)
display(b)

array([1, 2, 3, 4])

array([1.3, 3.4, 5.6, 7.8])

In [7]:
b = np.ones((3,3))    # Array of all ones
display(b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
c = np.full((3,3), 7)  # Constant array
display(c)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [9]:
d = np.eye(3)# Create a 2x2 identity matrix
display(d)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
e = np.random.random((3,3))  # Array filled with random values
display(e)

array([[0.30944245, 0.65491664, 0.7425433 ],
       [0.19674976, 0.69495179, 0.8735585 ],
       [0.30751887, 0.21767118, 0.9766961 ]])

### Attributes of Arrays

In [11]:
a = np.arange(100).reshape(10, 10)
display(a.shape)
display(a.dtype)
display(a.size)
display(a.ndim)

(10, 10)

dtype('int64')

100

2

### Random Values

In [12]:
x1 = np.random.randint(10, size=6)

In [13]:
display(x1)

array([2, 4, 3, 3, 6, 4])

In [14]:
x2 = np.random.randn(10)
display(x2)

array([ 1.15260768,  1.17582628, -0.23217445, -0.59398333, -1.45929787,
        1.47651515, -1.90008674,  1.36998163,  0.0291776 , -0.84184082])

In [15]:
x3 = np.random.random(10)
display(x3)

array([0.60123577, 0.865099  , 0.96462937, 0.76837038, 0.83207236,
       0.95158877, 0.00859913, 0.40203759, 0.22521091, 0.0792537 ])

In [16]:
x2 = np.random.randint(10, size=(3, 4))

In [17]:
display(x2)

array([[0, 3, 4, 5],
       [7, 0, 0, 9],
       [4, 5, 1, 0]])

In [18]:
x3 = np.random.randint(3, size=(3, 4, 5))

In [19]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


### Indexing of Arrays

In [20]:
a = np.arange(10)**3

display(a)
display(a[2])
display(a[2:5])
display(a[-5:-2])

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

8

array([ 8, 27, 64])

array([125, 216, 343])

Create the following rank 2 array with shape (3, 4)

In [21]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
display(a)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Use slicing to pull out the subarray consisting of the first 2 rows, and columns 1 and 2; b is the following array of shape (2, 2)

In [22]:
b = a[:2, 1:3]
display(b)

array([[2, 3],
       [6, 7]])

A slice of an array is a view into the same data, so modifying it will modify the original array

In [23]:
display(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
display(a[0, 1])   # Prints "77"

2

77

### Vector Operations

In [24]:
a = np.arange(6).reshape(1,6)
b = np.arange(6).reshape(6,1)

display("Array for 'a':", a)
display("Array for 'a':", b)
a_b_product = np.dot(a,b)
display(a_b_product)

"Array for 'a':"

array([[0, 1, 2, 3, 4, 5]])

"Array for 'a':"

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

array([[55]])

### Element Wise Dot Product

In [25]:
a = np.arange(6).reshape(1,6)
b = np.arange(6).reshape(1,6)

np.multiply(a, b)

array([[ 0,  1,  4,  9, 16, 25]])